### ISSUE TITLE
Add flag to check mutation sources against compile_commands.json

### ISSUE THREAD

**Issue by JamesLee-Jones** [mc-imperial/dredd#229]
When mutating a project, Dredd takes in a `compile_commands.json` file as well as a list of files that should be mutated. This approach is okay for smaller projects but can be impractical for mutating large project. It is also not always suitable to include all .c or .cc files as some may only be used for OS specific features. This can lead to errors when mutating projects were this is the case.

To solve this problem, a flag should be added to Dredd that works as follows:
- If `compile_commands.json` is passed and no .c or .cc files  are passed to Dredd, then Dredd should mutate all files present in `compile_commands.json`.
- If `compile_commands.json` is passed and files are passed to Dredd, these files should be mutated as normal, but a warning should be given if one of the files passed is not present in `compile_commands.json`.

**Comment by JamesLee-Jones** [comment]
[The documentation for `ClangTool`](https://clang.llvm.org/doxygen/classclang_1_1tooling_1_1ClangTool.html#a70bdbfa3038ea2c2ca72cf87be6ac8ba) claims that 'if a source files is not found in Compilations, it is skipped'. However, when attempting to apply Dredd to [tint](https://dawn.googlesource.com/tint), `src/tint/utils/command/command_windows.cc` is modified despite this file not appearing in `compile_commands.json`.

**Comment by JamesLee-Jones** [comment]
If you empty `compile_commands.json` to be just `[]`, then all files get skipped as expected. This can be demonstrated with the math library example. However, if an entry is only one entry is left and the rest are removed (for example, the entry for `math/src/exp.cc`), all files still gets processed by Dredd. This means `ClangTool` is not checking for inclusion as expected.

**Comment by JamesLee-Jones** [comment]
The check whether the file exists in the compilation database happens [here](https://clang.llvm.org/doxygen/Tooling_8cpp_source.html#l00569).

**Comment by JamesLee-Jones** [comment]
Adding the following to main.cc prints the result of `getCompileCommands` for each source file.
```
  for (const auto& str : options.get().getSourcePathList()) {
    std::cout << clang::tooling::getAbsolutePath(str) << ":" << std::endl;
    for (auto comp_command : options.get().getCompilations().getCompileCommands(clang::tooling::getAbsolutePath(str))) {
      std::cout << " - Filename: " << comp_command.Filename << std::endl;
      std::cout << " - Output: " << comp_command.Output << std::endl;
      std::cout << " - Directory: " << comp_command.Directory << std::endl;
      std::cout << " - CommandLine:" << std::endl;
      for (auto command : comp_command.CommandLine) {
        std:: cout << "   - " << command << std::endl;
      }
    }
  }
```

Using the math example with only the `exp.cc` command in `compile_commands.json`, this prints:
```
/home/jlj/dev/dredd/examples/math/math/src/exp.cc:
 - Filename: /home/jlj/dev/dredd/examples/math/math/src/exp.cc
 - Output: math/CMakeFiles/math.dir/src/exp.cc.o
 - Directory: /home/jlj/dev/dredd/examples/math/build
 - CommandLine:
   - /home/jlj/dev/dredd/third_party/clang+llvm/bin//clang++
   - --driver-mode=g++
   - -I/home/jlj/dev/dredd/examples/math/math/include
   - -c
   - --
   - /home/jlj/dev/dredd/examples/math/math/src/exp.cc
/home/jlj/dev/dredd/examples/math/math/src/number_theoretic.cc:
 - Filename: /home/jlj/dev/dredd/examples/math/math/src/number_theoretic.cc
 - Output: math/CMakeFiles/math.dir/src/exp.cc.o
 - Directory: /home/jlj/dev/dredd/examples/math/build
 - CommandLine:
   - /home/jlj/dev/dredd/third_party/clang+llvm/bin//clang++
   - --driver-mode=g++
   - -I/home/jlj/dev/dredd/examples/math/math/include
   - -c
   - --
   - /home/jlj/dev/dredd/examples/math/math/src/number_theoretic.cc
/home/jlj/dev/dredd/examples/math/math/src/trig.cc:
 - Filename: /home/jlj/dev/dredd/examples/math/math/src/trig.cc
 - Output: math/CMakeFiles/math.dir/src/exp.cc.o
 - Directory: /home/jlj/dev/dredd/examples/math/build
 - CommandLine:
   - /home/jlj/dev/dredd/third_party/clang+llvm/bin//clang++
   - --driver-mode=g++
   - -I/home/jlj/dev/dredd/examples/math/math/include
   - -c
   - --
   - /home/jlj/dev/dredd/examples/math/math/src/trig.cc
Processing /home/jlj/dev/dredd/examples/math/math/src/exp.cc
Processing /home/jlj/dev/dredd/examples/math/math/src/number_theoretic.cc
Processing /home/jlj/dev/dredd/examples/math/math/src/trig.cc
```

I suspect this is because the includes directory that is used when compiling `exp.cc` still contains `number_theoretic.h` and `trig.h`.
